<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="Pine_Branch_Test" Id="{bdfe5762-88cd-45bf-898f-fd5def4aba6d}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Pine_Branch_Test
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[// Pine branch test by Alan from his laptop. ]]></ST>
    </Implementation>
    <LineIds Name="Pine_Branch_Test">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>